version: '4.0'

services:

  calculation:
    build:
      context: ./calculations
    volumes:
      - data:/shared_data
      - ./calculations/src:/app/src

  fastapi:
    container_name: fastapi
    build:
      context: ./fastapi
    volumes:
      - data:/shared_data
      - ./fastapi/src:/app/src
    ports:
      - "80:80"

  
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    environment:
      # This is the required way to set a timezone on macOS and differs from the Linux compose file
      - TZ=Europe/Berlin
    volumes:
      - ./homeassistant_config:/config
    restart: always
    ports:
      # Also required for macOS since the network directive in docker-compose does not work
      - "8123:8123"
    depends_on:
      - fastapi

volumes:
  data:
