
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors/
#template: !include_dir_merge_list template/

python_script:

#logger:
#  default: info

logger:
  default: warning
  logs:
    homeassistant.components.rest: debug

